#!/bin/bash
git submodule update --init
BASE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "$BASE/scripts/tool.sh"
source "$BASE/scripts/init.sh"

ExportEnvs
EnvInit
InitEnvSource
InitEnvCommand