#!/bin/bash
_BASE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "${_BASE}/../scripts/tool.sh"
[ ! tool::pre_install_check ] && exit 1

VERSION='3.27.8'
[ -v 1 -a -n "$1" ] && VERSION="$1"
DOWNLOAD_URL="https://github.com/Kitware/CMake/releases/download/v${VERSION}/cmake-${VERSION}-linux-x86_64.tar.gz"

tool::download $DOWNLOAD_URL $APP $VERSION
tool::tar_extract $APP $VERSION install
tool::append_binary_path $APP bin
tool::update_install_link $APP $VERSION
