#!/bin/bash
BASE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)
source "${BASE}/../scripts/tool.sh"
[ ! tool::check_install ] && exit 1

VERSION='3.27.7'
[ -v 1 -a -n "$1" ] && VERSION="$1"
DOWNLOAD_URL="https://github.com/Kitware/CMake/releases/download/v${VERSION}/cmake-${VERSION}-linux-x86_64.tar.gz"

tool::download $DOWNLOAD_URL CMAKE $VERSION
tool::tar_extract CMAKE $VERSION
tool::append_binary_path CMAKE $VERSION bin