alias ll='ls -lGh'

# git alias
alias ga='git add'
alias gaa='git add --all'
alias gc='git commit'
alias gp='git push'
alias gpu='git push -u origin'
alias gl='git pull'
alias gs='git status'
alias gcm='git commit -m'
alias gd='git diff'
alias gb='git branch'
alias gbd='git branch -D'
alias glg='git log'
alias gck='git checkout'
alias gckm='git checkout master'
alias gckb='git checkout -b'
alias gmm='git merge master'

# mvn alias
alias mvnp='mvn clean package'
alias mvnd='mvn clean deploy'
alias mvnt='mvn dependency:tree'

# arc
alias arcf='arc feature'
alias arcd='arc diff master'
alias arcp='arc diff --preview master'
alias arcl='arc land --onto master'
